### ISSUE TITLE
First token not included in tokens collection when parsing statements

### ISSUE THREAD

**Issue by GaidenFocus** [bruce-dunwiddie/tsql-parser#3] opened 2018-01-11 23:24 UTC
This is really cool.  What I started to make and then cried and searched Google and found it.  Good stuff.  One issue though, it's not including the first word 'DECLARE'!

I traced it, it finds it, but when I load the tokens to a list it skips it!  Haven't fixed it yet, but will let you know if I do.  If you know the answer already, hit me up!

sovietmafioso@gmail.com

Thanks!

**Comment by bruce-dunwiddie** [comment] 2018-01-11 23:35
interesting. I'll write a test. should be something simple silly to solve. then I'll try to wrap up whatever I had going in this dev branch and push a new release, hopefully within a week or so. thanks for the feedback.

**Comment by bruce-dunwiddie** [comment] 2018-01-12 00:20
I'm not able to reproduce what I understand from your description using the released NuGet version or the dev branch source, see attached [Program.cs](https://github.com/bruce-dunwiddie/tsql-parser/files/1624562/Program.cs.txt) . Maybe it's in how you're loading the list? Can you give me a reproduction?

**Comment by GaidenFocus** [comment] 2018-01-12 14:13
It seems only when you have a DECLARE at top, it leaves out the first DECLARE.

`		public qcQuery(string query)
		{
			Text = query;
			Statements = TSQLStatementReader.ParseStatements(query, includeWhitespace: true);
		}
`

[https://image.ibb.co/b1xQhR/showing.png](url)

**Comment by bruce-dunwiddie** [comment] 2018-01-12 15:18
ok, that's at the statement level. maybe the token just isn't getting added to the tokens collection. I'll see if I can reproduce that. thank you.

**Comment by bruce-dunwiddie** [comment] 2018-01-13 22:22
I've released a new version with the fix for this issue, https://www.nuget.org/packages/TSQL.Parser/1.1.1 .

**Closed by bruce-dunwiddie** 2018-01-13 22:22 UTC
